# Generated by Django 5.1.7 on 2025-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZamanTakibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('baslangic', models.DateTimeField()),
                ('bitis', models.DateTimeField()),
            ],
        ),
    ]
