# Generated by Django 5.1.7 on 2025-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0004_taskprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprompt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
