# Generated by Django 5.1.7 on 2025-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprompt',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
