# Generated by Django 5.1.7 on 2025-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0009_alter_taskprompt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
